// Generated by LiveScript 1.2.0
var root, onYouTubeIframeAPIReady, injectScriptTag;
root = typeof global != 'undefined' && global !== null ? global : window;
root.ytplayer = null;
root.videoID = null;
onYouTubeIframeAPIReady = root.onYouTubeIframeAPIReady = function(){
  console.log('youtube API loaded!');
  if (root.ytplayer == null) {
    return root.ytplayer = new YT.Player('ytplayer', {
      height: '100',
      width: '640',
      videoId: root.videoID
    });
  }
};
Template.mktimings.lyricLines = function(){
  var lines, line;
  lines = this.lyricText.split('\n');
  return (function(){
    var i$, ref$, len$, results$ = [];
    for (i$ = 0, len$ = (ref$ = lines).length; i$ < len$; ++i$) {
      line = ref$[i$];
      results$.push({
        line: line
      });
    }
    return results$;
  }());
};
injectScriptTag = function(src, id){
  var tag, firstScriptTag;
  tag = document.createElement('script');
  tag.src = src;
  tag.id = id;
  firstScriptTag = document.getElementsByTagName('script')[0];
  return firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
};
Template.mktimings.invokeAfterLoad = function(){
  root.videoID = this.videoID;
  if (root.YT != null || $('#ytScriptTag').length > 0) {
    console.log('already loaded');
    return '';
  }
  injectScriptTag('https://www.youtube.com/iframe_api', 'ytScriptTag');
  return '';
};