// Generated by LiveScript 1.2.0
var root, Songs, Lyrics, YoutubeSnippets;
root = typeof global != 'undefined' && global !== null ? global : window;
Songs = root.Songs = new Meteor.Collection("songs");
Lyrics = root.Lyrics = new Meteor.Collection("lyrics");
YoutubeSnippets = root.YoutubeSnippets = new Meteor.Collection("ytsnippets");