// Generated by LiveScript 1.2.0
var root, Songs, Lyrics, YoutubeSnippets, getLyricInfoSafe, getLyricInfo;
root = typeof global != 'undefined' && global !== null ? global : window;
Songs = root.Songs = new Meteor.Collection("songs");
Lyrics = root.Lyrics = new Meteor.Collection("lyrics");
YoutubeSnippets = root.YoutubeSnippets = new Meteor.Collection("ytsnippets");
Router.configure({
  layoutTemplate: 'layout'
});
getLyricInfoSafe = root.getLyricInfoSafe = function(lyricID){
  var error;
  try {
    if (lyricID == null || lyricID === '') {
      return null;
    }
    return getLyricInfo(lyricID);
  } catch (e$) {
    error = e$;
    return null;
  }
};
getLyricInfo = root.getLyricInfo = function(lyricID){
  var lyricDoc, lyricText, videoID, videoDoc, url, name;
  lyricDoc = Lyrics.findOne({
    _id: lyricID
  });
  lyricText = lyricDoc.text;
  videoID = lyricDoc.videoID;
  videoDoc = Songs.findOne({
    _id: videoID
  });
  url = videoDoc.url;
  name = videoDoc.name;
  return {
    lyricID: lyricID,
    videoID: videoID,
    url: url,
    name: name,
    lyricText: lyricText
  };
};
Router.map(function(){
  this.route('home', {
    path: '/',
    template: 'home'
  });
  this.route('playlyrics', {
    path: '/playlyrics',
    template: 'playlyrics',
    notFoundTemplate: 'loading',
    data: function(){
      return getLyricInfoSafe(this.params.lyricID);
    }
  });
  return this.route('mktimings', {
    path: '/mktimings',
    template: 'mktimings',
    notFoundTemplate: 'loading',
    data: function(){
      return getLyricInfoSafe(this.params.lyricID);
    }
  });
});